name: noren_oauth_wrapper
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  dio: ^5.9.0
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
